"""init

Revision ID: 13c57532018f
Revises: 
Create Date: 2023-10-20 21:38:50.576026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13c57532018f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_donors_email'), 'donors', ['email'], unique=False)
    op.create_index(op.f('ix_donors_id'), 'donors', ['id'], unique=False)
    op.create_index(op.f('ix_donors_name'), 'donors', ['name'], unique=False)
    op.create_index(op.f('ix_donors_phone'), 'donors', ['phone'], unique=False)
    op.create_table('donations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donor_id', sa.Integer(), nullable=True),
    sa.Column('resource_type', sa.Enum('MONEY', 'FOOD', 'CLOTHING', name='resourcetypeenum'), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['donor_id'], ['donors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_donations_id'), 'donations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_donations_id'), table_name='donations')
    op.drop_table('donations')
    op.drop_index(op.f('ix_donors_phone'), table_name='donors')
    op.drop_index(op.f('ix_donors_name'), table_name='donors')
    op.drop_index(op.f('ix_donors_id'), table_name='donors')
    op.drop_index(op.f('ix_donors_email'), table_name='donors')
    op.drop_table('donors')
    # ### end Alembic commands ###
